apiVersion: v1
kind: Service
metadata:
  name: concourse 
  labels:
    app: concourse 
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080 
      protocol: TCP
      name: concourse 
  selector:
    app: concourse 
